import requests, shutil

url = "http://localhost:8080/api/pdf"

payload = "<h1>Hello this is a test</h1>\n<img src=\"http://www2.sotong.io/static/tintin.jpg\">\n<a href=\"https://github.com/u1i/jogu\">generated by jogu</a>"

data = requests.request("POST", url, data=payload, stream=True)

with open('out.pdf', mode='w') as f:
    data.raw.decode_content = True
    shutil.copyfileobj(data.raw, f)
f.close()
